ingonyama-zk/icicle

.gitignore
README.md

Add gitignore

---

.github/ISSUE_TEMPLATE/bug_issue.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
.github/workflows/build.yml
README.md
build.rs

This PR:
- Adds a Github Action workflow for building the rust bindings and cuda library on each PR to ensure builds don't break
- Update README to reflect new usage of env variable for GPU type
- Adds Bug and Feature issue templates
- Adds a PR template

[FEAT]: Build Workflow + Templates

---

icicle/appUtils/ntt/ntt.cuh

~30x compared to current and ~10x speedup to [alternative batching](https://github.com/ingonyama-zk/icicle/commit/d29848e80e268ab5c65eff094e603ecf8d7b7864)

flattened 2 of 3 loops in batch ntt template

---

.gitignore
README.md
icicle/CMakeLists.txt
icicle/README.md

GoogleTest fix, updated readme

Fix for local machines GoogleTest and CMake (#70)

---

benches/msm.rs
benches/ntt.rs
src/test_bls12_381.rs
src/utils.rs

fix compilation for rust benches

hotfix compilation - rust bench

---

icicle/appUtils/poseidon/constants.cuh
icicle/appUtils/poseidon/poseidon.cuh

replace uint with uint32_t

---

.github/workflows/build.yml

Updates the build action to run on PRs that are targeting the `dev` branch as well

Update build action to include dev branch

---

.github/workflows/build.yml

This PR updates the build script to only run when a:
- PR is opened or marked as "ready for review"
- OR a commit contains changes in any of the following files/directories:
- icicle/**
- src/**
- Cargo.toml
- build.rs

Fix: build script

---

goicicle/curves/bn254/msm.go
goicicle/curves/bn254/msm_test.go

fix g2 test

---

icicle/curves/bls12_377/msm.cu
icicle/curves/bls12_381/msm.cu
icicle/curves/curve_template/msm.cu

This PR is a hotfix for `dev` branch latest changes
mentioned in  #32 
compilation issue at [5b504c44b7](https://github.com/ingonyama-zk/icicle/commit/5b504c44b786f71f6ec3701b69d0be166069a18)

large_msm compilation hotfix

---

icicle/appUtils/msm/msm.cu

bucket_method_msm - address 0 edge case

---

CITATION.cff

This PR adds a CITATION.cff file to allow proper citations in works that reference Icicle

Add citation to repo

---

goicicle/curves/bls12377/include/ntt.h
goicicle/curves/bls12377/ntt.go
goicicle/curves/bls12381/include/ntt.h
goicicle/curves/bls12381/ntt.go
goicicle/curves/bn254/include/ntt.h
goicicle/curves/bn254/ntt.go
goicicle/templates/hfiles/ntt.h.tmpl
goicicle/templates/ntt/ntt.go.tmpl
icicle/appUtils/ntt/ntt.cuh
icicle/curves/bls12_377/lde.cu
icicle/curves/bls12_381/lde.cu
icicle/curves/bn254/lde.cu
icicle/curves/curve_template/lde.cu.tmpl

remove decimation

---

README.md

This PR fixes broken links to the curve template and curve config files in README.md.
Resolves #164

Fix broken links in the readme

---

icicle/appUtils/poseidon/poseidon.cu

This PR reduces the number of modulo reductions in matrix multiplications and partial rounds inside Poseidon.
As a result, performance of height 30 tree builder on our lab machine improved from ~19.4 seconds to ~17.3 seconds.

Tree builder perf improvement

---

benches/msm.rs
benches/ntt.rs
examples/ntt/main.rs
src/test_bls12_377.rs

Fix CI - dont use deprecated package name 

---

curve_parameters/new_curve_script.py
icicle/curves/curve_template/params.cuh.tmpl

This PR fixes issues in nex curve python script
Resolves #186

add mont_r and mont_r_inv and fix args

---

.github/changed-files.yml
.github/workflows/main-build.yml
.github/workflows/main-format.yml
.github/workflows/main-test.yml

This PR:
- Adds C++/CUDA CI
- Adds conditional workflow runs based on changed files (see paths in [.github/changed-files.yml](https://github.com/ingonyama-zk/icicle/blob/dc33183cdaf2b2c71c1b91118608e9c469fdb6c9/.github/changed-files.yml))
Resolves #184

[CI]: Adds C++/CUDA CI and conditional workflow runs

---

README.md

Update docs based on #226
Resolves #

Make dependency instructions more clear

---

README.md

include colab

---

icicle/appUtils/poseidon/constants.cuh
icicle/appUtils/poseidon/poseidon.cu
icicle/appUtils/poseidon/poseidon.cuh
icicle/primitives/field.cuh
icicle/test.sh
icicle/utils/error_handler.cuh

C++/CUDA throws IcicleError
Resolves #213

C++/CUDA throws IcicleError

---

icicle/README.md
icicle/appUtils/msm/msm.cu
icicle/appUtils/ntt/ntt.cu
icicle/appUtils/poseidon/poseidon.cu
icicle/appUtils/poseidon/poseidon.cuh
icicle/appUtils/poseidon/poseidon_test.cu
icicle/test.sh
icicle/utils/vec_ops.cu
wrappers/rust/icicle-core/src/error.rs
wrappers/rust/icicle-core/src/msm/tests.rs
wrappers/rust/icicle-core/src/ntt/tests.rs

pr comments

---

icicle/CMakeLists.txt
icicle/utils/mont.cu
wrappers/rust/icicle-core/src/curve.rs
wrappers/rust/icicle-core/src/field.rs
wrappers/rust/icicle-core/src/tests.rs
wrappers/rust/icicle-core/src/traits.rs
wrappers/rust/icicle-curves/icicle-bls12-377/src/curve.rs
wrappers/rust/icicle-curves/icicle-bls12-381/src/curve.rs
wrappers/rust/icicle-curves/icicle-bn254/src/curve.rs
wrappers/rust/icicle-curves/icicle-bw6-761/src/curve.rs

change mont API

---

README.md
examples/ZKContainer.md
examples/rust/msm/README.md
examples/rust/ntt/README.md

This PR has an updated README for icicle repo

Update readme v1.0.0

---

examples/c++/msm/.devcontainer/Dockerfile
examples/c++/msm/CMakeLists.txt
examples/c++/msm/README.md
examples/c++/msm/compile.sh
examples/c++/msm/example.cu
examples/c++/msm/run.sh

This PR allows c++ MSM example to compile with new API
Resolves #

c++ msm uses new API

---

docs/docusaurus.config.js

fix dcos base url

---

docs/docs/icicle/primitives/overview.md

fix-primitives-links

---

.github/changed-files.yml

This PR fixes the glob pattern of changed files for rust

Fix the changed files glob pattern

---

README.md
docs/docs/icicle/overview.md

Removed the badge from:
1. readme
2. overview.md

Removed "machines using ICICLE" static badge 

---

README.md

Added v1.8's contributors to hall of fame

Update Hall of fame in 'README.md'

---

docs/sidebars.js

This PR adds multi GPU golang documentation to dev sidebar

add golang multigpu to sidebar

---

wrappers/rust/icicle-core/Cargo.toml
wrappers/rust/icicle-core/src/ntt/mod.rs
wrappers/rust/icicle-core/src/ntt/tests.rs
wrappers/rust/icicle-curves/icicle-bls12-377/Cargo.toml
wrappers/rust/icicle-curves/icicle-bls12-377/src/ntt/mod.rs
wrappers/rust/icicle-curves/icicle-bls12-381/Cargo.toml
wrappers/rust/icicle-curves/icicle-bls12-381/src/ntt/mod.rs
wrappers/rust/icicle-curves/icicle-bn254/Cargo.toml
wrappers/rust/icicle-curves/icicle-bn254/src/ntt/mod.rs
wrappers/rust/icicle-curves/icicle-bw6-761/Cargo.toml
wrappers/rust/icicle-curves/icicle-bw6-761/src/ntt/mod.rs
wrappers/rust/icicle-curves/icicle-curve-template/Cargo.toml
wrappers/rust/icicle-curves/icicle-curve-template/src/ntt/mod.rs

run releasedomain last and add assertion to test

---

docs/docs/icicle/polynomials/overview.md
docs/sidebars.js

Polynomial API documentation

---

docs/docs/icicle/rust-bindings/ecntt.md
docs/sidebars.js

rust ecntt docs

---

README.md

Updated hall of fame

---

.github/workflows/cpp_cuda.yml

This PR adds build args to the Cpp CI and adds grumpkin curve and stark252 field

[CI]: Update Cpp CI to include build args

---

docs/docs/icicle/golang-bindings/keccak.md
docs/docs/icicle/primitives/keccak.md
docs/docs/icicle/primitives/overview.md
docs/docs/icicle/rust-bindings/keccak.md
docs/sidebars.js
wrappers/rust/icicle-hash/src/keccak/mod.rs

keccak docs

---

wrappers/rust/icicle-core/src/ecntt/mod.rs

This PR fixes Rust ECNTT benches and tests
Resolves #

rust ecntt hotfix

---

docs/docusaurus.config.js

adds syntax highlighting to `rust` and `go`

syntax highlight

---

examples/ZKContainer.md

There was a broken link is linked to ZKContainer word.
Resolves #

Fix broken link

---

.github/changed-files.yml
.github/workflows/check-changed-files.yml
.github/workflows/examples.yml

This PR:
- Updates the CI to run on CI workflow file changes
- Updates examples CI to run on examples file changes

Update CI to run on some non-code changes

---

docs/docs/icicle/golang-bindings/msm.md
examples/golang/msm/README.md
examples/golang/msm/main.go
examples/golang/ntt/README.md
examples/golang/ntt/main.go
examples/golang/polynomials/README.md
examples/golang/polynomials/main.go

golang examples init

---

.github/workflows/test-deploy-docs.yml
docs/docs/icicle/primitives/poseidon.md

Fixes a link issue in docs preventing deployment

Fix link and correct path for running test deploy workflow

---

examples/c++/risc0/CMakeLists.txt
examples/c++/risc0/README.md
examples/c++/risc0/compile.sh
examples/c++/risc0/example.cu
examples/c++/risc0/run.sh

This new c++ example shows the basics of RISC0 protocol using our Polynomial API

RISC0 example using Polynomial API

---

docs/sidebars.js

Removed ZK containers from docs sidebar

---

icicle/include/fields/stark_fields/m31.cuh

This PR fixes `reduce` function and sets correct `nonresidue` in the`fp_config`

m31 fix reduce function

---

docs/docs/icicle/arch_overview.md
docs/docs/icicle/build_from_source.md
docs/docs/icicle/getting_started.md
docs/docs/icicle/install_cuda_backend.md
docs/docs/icicle/migrate_from_v2.md
docs/docs/icicle/programmers_guide/rust.md
examples/c++/install-and-use-icicle/README.md
examples/rust/install-and-use-icicle/README.md
examples/rust/install-and-use-icicle/src/main.rs
icicle/backend/cpu/src/curve/cpu_msm.hpp
icicle/include/icicle/errors.h
icicle/src/runtime.cpp

cuda-backend-branch: yshekel/license_client

Fix typo for license error and updated docs

---

docs/docs/introduction.md

intro edit

---

README.md

links and typos

---

README.md
icicle/include/icicle/curves/projective.h
icicle/include/icicle/fields/field.h
icicle/include/icicle/utils/modifiers.h
icicle/tests/test_curve_api.cpp
scripts/release/Dockerfile.ubi8
scripts/release/Dockerfile.ubi9
scripts/release/Dockerfile.ubuntu20
scripts/release/Dockerfile.ubuntu22
scripts/release/build_all.sh
scripts/release/build_release_and_tar.sh
wrappers/rust/icicle-core/src/msm/tests.rs

cuda-backend-branch: yshekel/faster_msm_compile_time

Release for cuda archs 75,80,86 for better compatability

---

icicle/backend/cpu/src/hash/cpu_keccak.cpp

General fixes including updated credit
cuda-backend-branch: yshekel/keccak_cuda

Keccak updates and fixes

---

icicle/backend/cpu/src/hash/cpu_merkle_tree.cpp
icicle/tests/test_hash_api.cpp

Error message for leaves size too large fixed

Hash-test-size-fix

---

icicle/include/api/hash.h
icicle/src/hash/CMakeLists.txt
wrappers/rust/icicle-hash/src/blake2s/mod.rs
wrappers/rust/icicle-hash/src/blake2s/tests.rs
wrappers/rust/icicle-hash/src/lib.rs

This PR updates the existing Blake2s implementation by integrating a C++ API and a Rust wrapper API.

blake2s cpp and rust API

---

wrappers/rust/icicle-core/src/poseidon/mod.rs
wrappers/rust/icicle-core/src/poseidon/tests.rs

cuda-backend-branch: yshekel/poseidon_init_constants

test poseidon hasher on multiple devices

---

docs/docs/icicle/primitives/hash.md
icicle/include/icicle/hash/poseidon.h

This PR is for add some poseidon descrpition in the appropriate hash.md.
Resolves #

Add some documentation on poseidon

---

docs/docusaurus.config.js

updated banner to show 3.1

---

docs/docusaurus.config.js

Dev docs banner update 3.1

---

wrappers/rust/Cargo.toml

bump rust crates version to 3.2.0

---

icicle/backend/cpu/src/field/cpu_vec_ops.cpp

- CPU vec-ops are using two threads less than available. 
- The intention was to reserve one for the main thread but this is redundant here since main thread is doing very little work.
- In addition, for a single core machine this is a bug, where 0 workers are used.

fix bug in CPU vec ops regarding nof workers

---

icicle/CMakeLists.txt
icicle/cmake/curve.cmake
icicle/cmake/field.cmake
icicle/cmake/setup.cmake
icicle/include/icicle/utils/log.h

- updated cmake for android cross compilation, including vulkan
- updated log.h for android

Support android and vulkan

---

docs/docs/grants.md

Update to the new 2025 grants

---

icicle/backend/cpu/src/curve/cpu_msm.hpp

Move initialization of the bucket_busy vectors to threads

---

wrappers/rust/icicle-fields/icicle-m31/src/quotient/mod.rs

This PR moves internal_samples outside accumulate function

move internal_samples outside accumulate function

---

docs/versioned_docs/version-2.8.0/icicle/primitives/msm.md
examples/c++/polynomial-multiplication/example.cpp
examples/rust/arkworks-icicle-conversions/src/main.rs
wrappers/rust/icicle-core/src/msm/mod.rs

This PR adds support for G2 point conversion in the ark Rust example

Support G2 point conversion in Rust example

---

icicle/src/quotient/quotient.cu

handle sample_size is zero

---

icicle/tests/test_field_api.cpp

Add tests for sumcheck with single input program
cuda-backend-branch: idan/sumchek_single_poly

tests for single poly input

---

.github/workflows/release.yml
scripts/release/build_all.sh

This PR fixes the release script and adds options for what to do in the release script

Fix release script

---

icicle/tests/test_hash_api.cpp

Removed MerkleTreeBasic test and its hash function HashSumBackend, as the latter does not serve as a good hash function which caused false failures in edge cases where randomly modifying the leaves can still possibly lead to the same output.
Changes:
Removed MerkleTreeBasic test from test_hash_api
Removed associated hash HashSumBackend

Remove MerkleTreeBasic test

---

.github/workflows/release.yml
docs/docs/icicle/rust-bindings/sumcheck.md
docs/sidebars.ts
docs/versioned_docs/version-3.5.0/icicle/rust-bindings/sumcheck.md
docs/versioned_sidebars/version-3.5.0-sidebars.json
icicle/backend/cpu/src/hash/cpu_blake2s.cpp
icicle/backend/cpu/src/hash/cpu_blake3.cpp
icicle/backend/cpu/src/hash/cpu_keccak.cpp
icicle/include/icicle/hash/hash_config.h
icicle/tests/test_hash_api.cpp

Add Sumcheck Rust Docs to v3.5.0 and latest

Sumcheck Rust Docs

---

examples/rust/poseidon2/src/main.rs

- Support any backend with '-d' flag
- Fix wrong input size and disable zero-padding

Fix poseidon2 example to support any backend

---

icicle/backend/cpu/src/hash/cpu_blake2s.cpp
icicle/backend/cpu/src/hash/cpu_blake3.cpp
icicle/backend/cpu/src/hash/cpu_keccak.cpp

Refactor hash names

---

icicle/backend/cpu/include/cpu_fri_backend.h
icicle/include/icicle/backend/merkle/merkle_tree_backend.h
icicle/include/icicle/fri/fri.h
icicle/include/icicle/fri/fri_transcript.h
icicle/include/icicle/hash/pow.h
icicle/include/icicle/merkle/merkle_tree.h
icicle/tests/test_field_api.cpp

This PR updates FRI frontend and CPU to use our already existing PoW implementation and adds tests for main device
cuda-backend-branch: feat/fri

FRI frontend and cpu changes

---

docs/versioned_docs/version-3.5.0/icicle/overview.md

updated users, grant program, and some text edits

[DOCS] Update Overview

---

docs/docs/icicle/rust-bindings/sumcheck.md
docs/sidebars.ts
docs/versioned_sidebars/version-3.6.0-sidebars.json

[FEAT] sumcheck rust example fix

---

docs/docs/icicle/getting_started.md
docs/versioned_docs/version-3.6.0/icicle/getting_started.md

add MCP to Getting started Guide
This PR...
Resolves #

Accessing ICICLE with MCP

---

icicle/include/icicle/fields/stark_fields/goldilocks.h
icicle/tests/test_field_api.cpp

This PR fixes the bug that existed in the storage sanity test testing the function from(bytes).
It also fixes the bug in the implementation of the from function in goldilocks.

Fixing bug in the from function in goldilocks and fixing the test for this function

---

.github/workflows/cpp-golang-rust.yml
icicle/src/runtime.cpp
wrappers/rust/icicle-runtime/src/memory.rs
wrappers/rust/icicle-runtime/src/runtime.rs
wrappers/rust/icicle-runtime/src/tests.rs

copy | rust

---

scripts/python/param_generation_for_from_func.py

This PR adds the script that is used to generate the required parameters by the from(bytes) function in the field class which are:
- unsigned reduced_digits_count
- storage_array<reduced_digits_count, limb_count> reduced_digits
- storage_array<mod_subs_count, 2 * limbs_count + 2> mod_subs

python script for generation params for from(bytes) function

---

wrappers/rust/icicle-runtime/src/memory.rs
wrappers/rust/icicle-runtime/src/runtime.rs
wrappers/rust/icicle-runtime/src/tests.rs

This PR adds support for using icicle_memset in icicle rust wrapper
Resolves #

[FEAT] Rust memset

---

icicle/include/icicle/fields/complex_extension.h
icicle/include/icicle/fields/cubic_extension.h

Fix mul_wide for clang 19+

---

docs/docusaurus.config.ts
docs/package-lock.json
docs/package.json

Update Docusaurus configuration to include Google Analytics tracking ID

---

scripts/release/build_all.sh
scripts/release/build_release_and_tar.sh

[FEAT] Release ubuntu and build for RTX 40XX,50XX

---

icicle/src/curves/ffi_extern.cpp
wrappers/rust/icicle-core/src/curve.rs
wrappers/rust/icicle-core/src/tests.rs

Add generator functions for projective points in FFI and Rust bindings

---

.github/workflows/cla.yml

This PR fixes the CLA workflow to not require team members from signing it

Fix team member check

---

.github/workflows/deploy-docs.yml

This PR fixes the deploy-docs workflow by checking out the repo before trying to use a reusable workflow from the repo

[CI] Fix deploy-docs workflow

---

docs/versioned_docs/version-3.9.0/start/architecture/libraries.md

2 more broken references fixed

---

icicle/src/hash/poseidon.cpp
icicle/src/hash/poseidon2.cpp

This PR fixes compilation for g++14.2.0

Fix compilation for g++14.2.0

---

icicle/backend/cpu/src/ring/cpu_jl_projection.cpp
icicle/include/icicle/backend/vec_ops_backend.h
icicle/include/icicle/jl_projection.h
icicle/src/jl_projection.cpp
icicle/tests/test_ring_api.cpp

Feat: generate JL-projection matrix rows

---

wrappers/rust/icicle-core/src/curve.rs
wrappers/rust/icicle-core/src/tests.rs

Curve Montgomery Conversion Fix for Host Memory

---

docs/docs/api/rust-bindings/lattice/pqc-ml-kem.md
docs/sidebars.ts
docs/versioned_docs/version-3.9.0/api/cpp/lattice/pqc_ml_kem.md
docs/versioned_docs/version-3.9.0/api/rust-bindings/lattice/pqc-ml-kem.md
docs/versioned_sidebars/version-3.9.0-sidebars.json

Add PQC documentation to 3.9.0

---

icicle/cmake/ring.cmake
icicle/cmake/target_editor.cmake
wrappers/rust/icicle-core/Cargo.toml
wrappers/rust/icicle-core/build.rs
wrappers/rust/icicle-core/src/jl_projection/mod.rs
wrappers/rust/icicle-core/src/jl_projection/tests.rs
wrappers/rust/icicle-core/src/lib.rs
wrappers/rust/icicle-rings/icicle-labrador/build.rs
wrappers/rust/icicle-rings/icicle-labrador/src/jl_projection/mod.rs
wrappers/rust/icicle-rings/icicle-labrador/src/lib.rs

This PR implements JL-projection API for scalars and polynomial-rings (for fused conjugation).

[FEAT] JL-projection Rust wrapper

---

.github/workflows/ci.yml
icicle/src/ntt.cpp

[FIX] typo in ci.yml

---

icicle/backend/cpu/src/ring/cpu_norm.cpp

cuda-backend-branch: fix/norm_check

consistent norm check

---

.github/changed-files.yml
wrappers/rust/icicle-core/src/matrix_ops/mod.rs
wrappers/rust/icicle-core/src/matrix_ops/tests.rs
wrappers/rust/icicle-rings/icicle-labrador/src/matrix_ops/mod.rs

[FIX] Matmul rust wrappers identify device memory and assert sizes

---

icicle/backend/cpu/src/ring/cpu_random_sampling.cpp

cuda-backend-branch: fix/random-sampling

fix random sampling small size bug
