- icicle/appUtils/ntt/ntt.cuh
reduces single ec/ntt time ~2x - seems redundant mult, as all tests maintain correctness
> removed redundant mult

- .gitignore
- README.md
- icicle/CMakeLists.txt
- icicle/README.md
1. Fixes CMake errors on local dev machines
2. Improves on hardcoded CUDA_ARH (fix for #67)
3. Adds troubleshooting section
Tested on 
- Cmake 
-    3.16
-    latest 3.26.3 
-  GCC-8, 9, 10
-  CUDA 
-    12.0, 
-    12.1 (update 1)
-  Hardware
-  RTX 3090Ti
-  Laptop 3050Ti
-  2080Ti
> Fix for local machines GoogleTest and CMake

- icicle/CMakeLists.txt
- icicle/curves/bls12_381/params.cuh
- icicle/primitives/test_kernels.cuh
This PR fixes the compilation of the Google tests.
The header with the curve configuration was not pointing on the correct path. 
Some static struct members needed a definition for solving linking problems.
Resolves #103
> Fix curve config location and link to some namespace struct members

- .github/workflows/build-dev.yml
This PR:
- Removes the use of github caching (which wasn't working properly)
- Moves linux build job to a self hosted runner
- Uses a network download with specific packages for Windows to shorten times
- Splits `main` and `dev` actions to ensure build badges are correctly shown
Resolves #119
> CI: Remove caching and move linux to self-hosted

- README.md
- icicle/CMakeLists.txt
This PR modifies `icicle/CMakeLists.txt` to set `CMAKE_CUDA_ARCHITECTURES` to `${CUDA_ARCH}` if the cmake version is less than 3.24.0, and `native` otherwise. This change has been successfully tested with cmake 3.22.1 but I can't confirm if even earlier versions of cmake work.
Resolves #159. Thanks to @jeremyfelder for coming up with the solution!
> Support cmake versions below 3.24.0

- icicle/appUtils/msm/msm.cu
This PR aims to fix batch MSM tests in `dev` at minimum and preferably make batched performance as good as single MSM performance. In which case we might only leave one function to avoid duplication of code between batched/single MSM
> Fixing batched MSM

- Dockerfile
- README.md
- icicle/README.md
- icicle/primitives/test.cu
> fix cuda test - remove boost

- icicle/appUtils/ntt/ntt.cuh
This PR fixes a div by 0 edge case in NTT when the number of elements is 1
> Fix: div by 0 when number of Elements is 1

- icicle/appUtils/msm/msm.cu
The issue is in name collisions so to avoid them, fictional template parameters have been added, which distinguish functions from different curves. A more permanent and systematic fix will follow
> Hotfix to go regression when 2 curves are imported

- scripts/hooks/pre-push
This PR excludes the Rust target directory from c/cpp/cuda file format checks
> Exclude target directory from format checks

- goicicle/curves/bls12377/msm_test.go
- goicicle/curves/bls12381/msm_test.go
- goicicle/curves/bn254/msm_test.go
- goicicle/curves/bw6761/msm_test.go
- goicicle/templates/msm/msm_test.go.tmpl
- icicle/appUtils/ntt/ntt.cuh
fix typos
test logs: `occured`-> `occurred`
icicle/appUtils/ntt/ntt.cuh: `lenght` -> `length`
> fix typos in logs

- icicle/appUtils/ntt/ntt.cuh
- icicle/primitives/affine.cuh
- icicle/primitives/field.cuh
- icicle/primitives/projective.cuh
- icicle/utils/mont.cuh
This PR resolves the problem occurring in gnark groth16 circuits that use more than one curve simultaneously. More specifically, verification fails due to `krs2` MSM being incorrect, in turn caused by `computeH` function returning incorrect result. On closer inspection it turned out that `template_normalize_kernel` [here](https://github.com/ingonyama-zk/icicle/blob/main/icicle/appUtils/ntt/ntt.cuh#L333) just doesn't launch. It does so silently, without throwing any errors or visible memory leaks. It does seem that the problem has to do with compilation because simply using the same kernel with a different name helps as well as only using a single curve. The "fix" in this PR just replaces a second use-case of `template_normalize_kernel` with a more correct Montgomery treatment …
> Two curve NTT correctness issue hotfix

- .github/workflows/main-format.yml
- .rustfmt.toml
- scripts/hooks/pre-push
- wrappers/rust/icicle-cuda-runtime/src/bindings.rs
This PR removes the need to add bindings.rs to the repo. 
Since it is a generated file, it should not be tracked in the repo. These changes allow for running cargo fmt on single files under the `wrappers/rust` directory
> Fix the need for a dummy bindings.rs file included in the repo

- icicle/README.md
- icicle/cuda-shell.nix
This PR introduces a Nix Shell configuration for easing the development of the ICICLE Core using Nix or NixOS. 
Changes:
1. Added instructions on how to use Nix Shell to create a development environment with all required dependencies and environmental variables.
2. Created `cuda-shell.nix` to configure Nix Shell with necessary CUDA related packages and environmental variables. Specifically, setting the `PATH`, `LD_LIBRARY_PATH`, `CUDA_PATH`, `CPATH`, `LIBRARY_PATH`, and `CMAKE_CUDA_COMPILER` associated with the CUDA toolkit.
This configuration allows us to build and run ICICLE Core more efficiently in Nix environment.
> Add Nix Shell Environment Configuration for CUDA

- icicle/CMakeLists.txt
- wrappers/rust/icicle-curves/icicle-bn254/build.rs
This PR moves `ingo_<curve>` archive output to the same directory as the original library output allowing rust build scripts to find it when a curve crate is used as a dependency
> Fix curve crates not building when used as dependency

- .github/workflows/main-build.yml
- README.md
This PR fixes the build badge to show the status of the `main` branch build status instead of the status of a PR branch against `main`
> Fix main build badge to be on push and not pr

- .github/workflows/main-build.yml
- .github/workflows/main-format.yml
- .github/workflows/main-test.yml
- examples/c++/Poseidon-hash/example.cu
- examples/c++/msm/example.cu
- examples/c++/multiply/example.cu
- examples/c++/ntt/example.cu
- icicle/CMakeLists.txt
- icicle/appUtils/msm/Makefile
- icicle/appUtils/msm/msm.cu
- icicle/appUtils/ntt/ntt.cu
- icicle/appUtils/ntt/ntt.cuh
- icicle/primitives/field.cu
- icicle/primitives/projective.cu
- icicle/utils/mont.cu
- icicle/utils/utils.h
- wrappers/rust/icicle-core/src/ntt/mod.rs
For exposed functions that are curve-specific, the expected symbol is based on the curve name.
For example MSMCuda becomes bn254MSMCuda for CURVE=bn254.
currently it is implemented via objcopy by redefining symbols after compilation.
This PR modifies the function names at preprocessing time instead.
For shared objects, objcopy doesn't work (since it cannot modify the dynsym section).
notes:
1. maybe utils/utils.h is not great because any repo probably has such a file. maybe icicle_utils?
2. the code is a little more cluttered because of this macro. 
example:   'extern "C" cudaError_t MSMCuda' becomes  'extern "C" cudaError_t CONCAT_EXPAND(CURVE, MSMCuda)'
> refactor: generate curve-specific function names with macro

- .gitignore
- icicle/appUtils/msm/msm.cu
refactor: consolidate msm and batch-msm implementations to one function  
- now batch-msm support parallel BM accumulation in addition to large triangle accumulation
> refactor: consolidate msm and batch-msm implementations to one function

- examples/rust/msm/Cargo.toml
- examples/rust/ntt/Cargo.toml
- wrappers/rust/icicle-core/Cargo.toml
- wrappers/rust/icicle-cuda-runtime/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bls12-377/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bls12-381/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bn254/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bw6-761/Cargo.toml
This PR fixes the examples issue on `dev` regarding versions not being available
> Add missed bump to dev

- examples/rust/msm/Cargo.toml
- examples/rust/ntt/Cargo.toml
This PR makes the rust examples dependencies local paths to make sure that our changes before tagging a version can be tested with these examples
> Fix: examples path deps

- .github/workflows/examples.yml
This PR adds a concurrency group to the examples CI workflow to ensure only one instance of it is running per branch.
This will allow checks on each following commit to run immediately instead of waiting for a previous (and outdated) commit's check to finish
> Add concurrency group to examples workflow

- examples/c++/ntt/README.md
- examples/c++/ntt/example.cu
Update to cover new NTT algorithms
> updates example compares Radix2 and MixedRadix NTTs

- examples/c++/pedersen-commitment/CMakeLists.txt
- examples/c++/pedersen-commitment/README.md
- examples/c++/pedersen-commitment/compile.sh
- examples/c++/pedersen-commitment/example.cu
- examples/c++/pedersen-commitment/run.sh
Show using Icicle's MSM to perform Pedersen commitment
> Pedersen commitment example in c++

- README.md
- docs/docs/icicle/overview.md
added on readme and on icicle overview
> Added badges

- .github/workflows/golang.yml
This PR adds the use of setup-go in the CI to ensure that `go` is installed properly and caches dependencies and build outputs by default
> Fix go setup in CI

- .github/workflows/rust.yml
- docs/docs/icicle/supporting-additional-curves.md
- icicle/appUtils/poseidon/constants/constants_template.h
- scripts/bump_rust_versions.sh
- scripts/hooks/pre-push
- wrappers/rust/icicle-core/Cargo.toml
- wrappers/rust/icicle-core/src/poseidon/mod.rs
- wrappers/rust/icicle-cuda-runtime/Cargo.toml
- wrappers/rust/icicle-cuda-runtime/build.rs
- wrappers/rust/icicle-curves/icicle-bls12-377/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bls12-377/src/poseidon/mod.rs
- wrappers/rust/icicle-curves/icicle-bls12-381/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bn254/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bn254/src/poseidon/mod.rs
- wrappers/rust/icicle-curves/icicle-bw6-761/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bw6-761/src/poseidon/mod.rs
- wrappers/rust/icicle-curves/icicle-curve-template/Cargo.toml
- wrappers/rust/icicle-curves/icicle-curve-template/build.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/curve.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/lib.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/msm/mod.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/ntt/mod.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/poseidon/mod.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/tree/mod.rs
- wrappers/rust/icicle-curves/icicle-curve-template/src/vec_ops/mod.rs
- wrappers/rust/icicle-curves/icicle-grumpkin/Cargo.toml
- wrappers/rust/icicle-curves/icicle-grumpkin/src/poseidon/mod.rs
This PR is a compilation of small improvements
- Lock bindgen version for `icicle-cuda-runtime`
- Add an error message when trying to build on Mac (or any non windows/linux machine)
- Add documentation and template files for adding new curve
- Add documentation on _params.cuh contents
- Add the script to bump all the rust crates versions to the same version
> Small features

- .github/workflows/release.yml
This PR fixes the release flow action
> Fix release flow with deploy key and caching

- Dockerfile
The go package resources have been updated in https://go.dev/dl/ and it leads to failure when executing `docker build -t icicle-demo .`
> update go install source in Dockerfile

- icicle/CMakeLists.txt
Speed up CUDA c++ compile time using multi-threaded compilation (--split-compile flag).
The tests on 8 core machine show ~2x acceleration.
Compiling c++ takes long time
> Use multi-threaded CUDA compilation to spped up compilation

- icicle/appUtils/msm/msm.cu
- icicle/appUtils/msm/msm.cuh
- icicle/appUtils/msm/tests/msm_test.cu
- icicle/primitives/field.cuh
- icicle/utils/mont.cuh
- wrappers/golang/build.sh
- wrappers/golang/core/ntt.go
- wrappers/golang/core/ntt_test.go
- wrappers/golang/curves/bls12377/g2_msm_test.go
- wrappers/golang/curves/bls12377/include/g2_msm.h
- wrappers/golang/curves/bls12377/include/msm.h
- wrappers/golang/curves/bls12377/msm_test.go
- wrappers/golang/curves/bls12381/g2_msm_test.go
- wrappers/golang/curves/bls12381/include/g2_msm.h
- wrappers/golang/curves/bls12381/include/msm.h
- wrappers/golang/curves/bls12381/msm_test.go
- wrappers/golang/curves/bn254/g2_msm_test.go
- wrappers/golang/curves/bn254/include/g2_msm.h
- wrappers/golang/curves/bn254/include/msm.h
- wrappers/golang/curves/bn254/msm_test.go
- wrappers/golang/curves/bw6761/g2_msm_test.go
- wrappers/golang/curves/bw6761/include/g2_msm.h
- wrappers/golang/curves/bw6761/include/msm.h
- wrappers/golang/curves/bw6761/msm_test.go
- wrappers/golang/internal/generator/templates/include/g2_msm.h.tmpl
- wrappers/golang/internal/generator/templates/include/msm.h.tmpl
- wrappers/golang/internal/generator/templates/msm_test.go.tmpl
(1) MSM method now takes points and scalars params by const.
This is required to be able to compute MSM on polynomial coefficients, that are internal to the polynomial objects, thus can only be accessed by const, to avoid unexpected writes.
(2) NTTAlgorithm field added to golang NTTConfig
> (1) MSM scalars and points params are const and (2) missing NTTAlgorithm in golang NTTConfig

- icicle/appUtils/keccak/Makefile
- icicle/appUtils/keccak/keccak.cu
- icicle/appUtils/keccak/keccak.cuh
- icicle/appUtils/keccak/test.cu
This PR adds support for Keccak-256 and Keccak-512. It only adds them in c++. There is no way of adding rust or golang wrappers  rn as it requires having an `icicle-common` create / mod
> Add Keccak hash function

- icicle/appUtils/ntt/kernel_ntt.cu
- icicle/appUtils/ntt/ntt.cu
- icicle/appUtils/ntt/ntt.cuh
- icicle/appUtils/ntt/ntt_impl.cuh
- icicle/appUtils/ntt/thread_ntt.cu
- icicle/utils/utils_kernels.cuh
- wrappers/golang/curves/bls12377/include/ntt.h
- wrappers/golang/curves/bls12381/include/ntt.h
- wrappers/golang/curves/bn254/include/ntt.h
- wrappers/golang/curves/bw6761/include/ntt.h
- wrappers/golang/internal/generator/templates/include/ntt.h.tmpl
Make NTT input const pointer so that polynomial API implementation can call it with internal memory pointer.
> fix: NTT input is const

- icicle/appUtils/ntt/ntt.cu
- This PR is a hotfix for large ECNTTs of size 2^18 x 64 and above
- Rust bindings benchmarks and correctness test against Arkworks to come in subsequent PRs
Resolves #
> hotfix for large ecntt

- icicle/primitives/projective.cuh
- icicle/tests/polynomial_test.cu
This PR adds a "dummy verifier" to Groth16 and a test which swaps G2 for the scalar field. This allows checking correctness without pairings. One change to the prover that was needed for everything to work is zero padding to the power of two without which verifier fails.
One small fix also added which corrects `Projective::from_affine` function for zero input.
> Groth16 test with verification

- icicle/appUtils/ntt/ntt.cu
- wrappers/rust/icicle-core/src/ntt/mod.rs
- wrappers/rust/icicle-core/src/ntt/tests.rs
Due to Rust's ownership rules, we can't run NTT inplace using the [`ntt`](https://github.com/ingonyama-zk/icicle/blob/v1.9.1/wrappers/rust/icicle-core/src/ntt/mod.rs#L139) function. Which is why we saw a need to add a separate function a couple of times.
Incidentally an issue with radix-2 NTT was found when ran inplace, `__syncthreads()` was used in reverse order kernel as if it was a global barrier for all blocks and not block-local one. Thus data race happened that is fixed by this PR.
> NTT inplace in Rust

- wrappers/golang/curves/bls12377/ntt_test.go
- wrappers/golang/curves/bls12381/ntt_test.go
- wrappers/golang/curves/bn254/ntt_test.go
- wrappers/golang/curves/bw6761/ntt_test.go
- wrappers/golang/internal/generator/templates/ntt_test.go.tmpl
This PR fixes TestNttDeviceAsync by adding a missing call to initDomain
Resolves #
> Fix Golang TestNttDeviceAsync

- wrappers/golang/core/slice.go
- wrappers/golang/core/slice_test.go
This PR adds the capability to slice a DeviceSlice, allowing portions of data that are already on the device to be reused.
Additionally, this PR removes the need for a HostSlice underlying type to implement a Size function and uses unsafe.Sizeof instead. This together with #407 will allow direct usage of gnark-crypto types with HostSlice without the need for converting to ICICLE types
> [FEAT]: golang device slice ranges

- icicle/utils/vec_ops.cu
- icicle/utils/vec_ops.cuh
- wrappers/rust/icicle-core/src/ntt/tests.rs
- wrappers/rust/icicle-core/src/vec_ops/mod.rs
This PR adds an extern C link to the transpose kernel, now in vec_ops.cu.
Also Rust binding, and I updated the test check_ntt_batch to use the new transpose function.
The test passes.
Resolves #
> transpose kernel in vec_ops and rust binding

- icicle/appUtils/msm/msm.cu
This PR fixes an underflow in `get_optimal_c` when bitsize is less than 16 and adds `max(1,NUM_THREADS)` to prevent div by 0 when calculating NUM_THREADS
> [PATCH]: Fix underflow and div by 0

- docs/docs/icicle/golang-bindings/vec-ops.md
- docs/docs/icicle/rust-bindings/vec-ops.md
- wrappers/golang/core/vec_ops.go
- wrappers/golang/core/vec_ops_test.go
At some point we deleted Montgomery flag from vector ops config in C++ code and Rust bindings, but it stayed in golang bindings. This is fixed by this PR. Probably best to merge before releasing V2 as this is strictly speaking a breaking change.
> Fix golang vec ops config

- icicle/include/fields/stark_fields/babybear.cuh
- wrappers/rust/icicle-fields/icicle-babybear/Cargo.toml
- wrappers/rust/icicle-fields/icicle-babybear/src/ntt/mod.rs
This PR adds a test that shows the consistency of our baby bear implementation with both plonky3 and risc0. Initially I assumed that the difference in non-residues (-11 vs. 11) will affect the correctness but actually they are equivalent.
> Plonky3 babybear consistency

- go.mod
This PR fixes the issue of v2 ICICLE not being discovered by Go's packaging service by adding the required "v2" to the module path: https://go.dev/doc/modules/release-workflow#breaking
> [PATCH]: Update module with v2 versioning

- icicle/include/ntt/ntt_impl.cuh
- icicle/src/ntt/kernel_ntt.cu
- icicle/src/ntt/ntt.cu
- wrappers/rust/icicle-core/src/ntt/mod.rs
- wrappers/rust/icicle-core/src/ntt/tests.rs
The bug was in how twiddles array is indexed when multiplied by a mixed (M) vector to implement (I)NTT on cosets.
The fix is to use the DIF-digit-reverse to know which element in the natural (N) vector, moved to index 'i' in the M vector. This is emulating a DIT-digit-reverse (which is mixing like a DIF-compute) reorder of the twiddles array and element-wise multiplication without reordering the twiddles memory.
> fix: bug regarding MixedRadix coset NTT for NM/MN ordering

- wrappers/rust/icicle-core/src/ecntt/mod.rs
- wrappers/rust/icicle-core/src/msm/mod.rs
- wrappers/rust/icicle-core/src/msm/tests.rs
- wrappers/rust/icicle-core/src/ntt/mod.rs
- wrappers/rust/icicle-curves/icicle-bls12-377/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bls12-377/benches/ecntt.rs
- wrappers/rust/icicle-curves/icicle-bls12-377/benches/msm.rs
- wrappers/rust/icicle-curves/icicle-bls12-377/benches/ntt.rs
- wrappers/rust/icicle-curves/icicle-bls12-381/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bls12-381/benches/ecntt.rs
- wrappers/rust/icicle-curves/icicle-bls12-381/benches/msm.rs
- wrappers/rust/icicle-curves/icicle-bls12-381/benches/ntt.rs
- wrappers/rust/icicle-curves/icicle-bn254/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bn254/benches/msm.rs
- wrappers/rust/icicle-curves/icicle-bn254/benches/ntt.rs
- wrappers/rust/icicle-curves/icicle-bw6-761/Cargo.toml
- wrappers/rust/icicle-curves/icicle-bw6-761/benches/msm.rs
- wrappers/rust/icicle-curves/icicle-bw6-761/benches/ntt.rs
- wrappers/rust/icicle-curves/icicle-grumpkin/Cargo.toml
- wrappers/rust/icicle-curves/icicle-grumpkin/benches/msm.rs
Rust idiomatic benches for EC NTT, NTT, MSM
Resolves #
> rust classic benches with Criterion for ecntt/msm/ntt

- docs/docs/icicle/core.md
- docs/docs/icicle/golang-bindings.md
- docs/docs/icicle/golang-bindings/ecntt.md
- docs/docs/icicle/golang-bindings/msm-pre-computation.md
- docs/docs/icicle/golang-bindings/msm.md
- docs/docs/icicle/golang-bindings/multi-gpu.md
- docs/docs/icicle/golang-bindings/ntt.md
- docs/docs/icicle/golang-bindings/vec-ops.md
- docs/docs/icicle/introduction.md
- docs/docs/icicle/multi-gpu.md
- docs/docs/icicle/overview.md
- docs/docs/icicle/polynomials/overview.md
- docs/docs/icicle/primitives/msm.md
- docs/docs/icicle/primitives/ntt.md
- docs/docs/icicle/primitives/poseidon.md
- docs/docs/icicle/rust-bindings.md
- docs/docs/icicle/rust-bindings/ecntt.md
- docs/docs/icicle/rust-bindings/msm-pre-computation.md
- docs/docs/icicle/rust-bindings/msm.md
- docs/docs/icicle/rust-bindings/ntt.md
- docs/docs/icicle/rust-bindings/polynomials.md
- docs/docs/icicle/rust-bindings/vec-ops.md
- docs/docs/introduction.md
- docs/package-lock.json
- docs/sidebars.js
- wrappers/golang/README.md
This PR tidies up docs and updates golang build instructions
> [DOCS]: Tidy up docs

- examples/c++/polynomial-api/example.cu
- icicle/src/fields/CMakeLists.txt
- icicle/src/polynomials/cuda_backend/polynomial_cuda_backend.cu
- icicle/tests/CMakeLists.txt
- icicle/tests/polynomial_test.cu
fixing:
(1) not building polynomials and tests for grumpkin curve (no NTT)
(2) polynomial API C++ example compilation and (when compilation is fixed) memory corruption
(3) bug fix in poly CUDA backend regarding transformation to evaluations in some cases
> fix: bug regarding polynomial evaluations view in CUDA backend

- icicle/cmake/Common.cmake
This PR modifies icicle/cmake/Common.cmake to set CMAKE_CUDA_ARCHITECTURES to ${CUDA_ARCH} if the user defines the arch, to set CMAKE_CUDA_ARCHITECTURES to native if the cmake version is greater than or equal to 3.24.0. This change has been successfully tested with cmake 3.22.0 and 3.25.2.
Resolves #167.
> Allow overriding compiler's chosen GPU arch via cmake

- icicle/src/ntt/kernel_ntt.cu
- icicle/src/ntt/thread_ntt.cu
in some cases 32b values would wrap around and cause invalid accesses to wrong elements and memory addresses
> fix: ntt mixed-radix bug regarding large ntts (and/or batch)

- icicle/src/msm/msm.cu
This PR fixes 2 things:
1. Removes the assertion regarding the precompute factor needing to be a power of 2. There is no such requirement and it works just fine for other values too.
2. Fixes the average bucket size for the large buckets threshold - it depends on the precompute factor.
> precompute bug fix

- examples/c++/polynomial-api/CMakeLists.txt
- examples/c++/polynomial-api/example.cu
This PR...
Added an example for simple commit that makes use of polynomial views. 
Output attached
```
Example: a) commit with Polynomial views [(f1+f2)^2 + (f1-f2)^2 ]_1 = [4 (f1^2+ f_2^2)]_1
Example: b) commit with Polynomial views [(f1+f2)^2 - (f1-f2)^2 ]_1 = [4 f1 *f_2]_1
Setup: Generating mock SRS
Setup: SRS of length 1025 generated and loaded to device. Took: 19557 milliseconds
Setup: Generating polys (on device) f1,f2 of log degree 10
Setup: Gen poly done. Took: 7 milliseconds
Computing constraints..start 
Computing constraints..done. Took: 0 milliseconds
Computing Commitments with poly view
Commitments done. Took: 29 milliseconds
commitment [(f1+f2)^2 + (f1-f2)^2]_1:
[x: 0x1e35d81da10e5026dacdd907d6ed0dde673de449ff8c0137ec6acbfd6b1dfe1b, y: …
```
> added example cpp:  example_commit_with_device_memory_view()

- docs/docs/icicle/primitives/poseidon.md
> chore: remove repeat word

- docs/docs/icicle/primitives/poseidon.md
Fixed 3 images shown in low quality - i have recreated the 3 images - please check me to see that i have not made a mistake
> recreated images for poseidon.md

- icicle/src/ntt/ntt.cu
- wrappers/rust/icicle-core/src/ecntt/tests.rs
This PR solves an issue for large ecntt where cuda blocks are too large and cannot be assigned to SMs. The fix is to reduce thread count per block and increase block count in that case.
> fix large (>512 elements) ecntt issue

- icicle/include/fields/field.cuh
adding a `num_bits()` function similar to https://github.com/arkworks-rs/algebra/blob/dcf73a5f9610ba9d16a3c8e0de0b3835e5e5d5e4/ff/src/biginteger/mod.rs#L482
this could be useful for small field optimizations
Resolves #
> feat: add `num_bits()` function

- icicle_v3/backend/cpu/include/tasks_manager.h
Added tasks_manager.h - a small library to aid multithreaded CPU coding.
> Add tasks manager classes to ease multithreading for cpu

- wrappers/rust/icicle-cuda-runtime/build.rs
This PR adds conditional compilation attributes to the `cuda_include_path` and `cuda_lib_path` functions to handle cases where the target OS is neither Windows nor Linux. Previously, the functions returned mismatched types, causing compilation errors when the target OS was unsupported. The added code now explicitly panics with a descriptive error message in such cases, improving code clarity and error handling.
1. **`cuda_include_path` function:**
- Added `#[cfg(not(any(target_os = "windows", target_os = "linux")))]` conditional attribute to handle unsupported OS cases.
- Included a panic with the message "Currently, ICICLE can only be built for Windows or Linux".
2. **`cuda_lib_path` function:**
- Added `#[cfg(not(any(target_os = "windows", target_os = "linux")))]` conditional attribute …
> Panic Instead Of Mismatched Types Error

- docs/docs/icicle/primitives/msm.md
- docs/docs/icicle/rust-bindings/msm.md
- icicle/backend/cpu/src/curve/cpu_msm.hpp
- icicle/include/icicle/api/babybear.h
- icicle/include/icicle/api/bls12_377.h
- icicle/include/icicle/api/bls12_381.h
- icicle/include/icicle/api/bn254.h
- icicle/include/icicle/api/bw6_761.h
- icicle/include/icicle/api/grumpkin.h
- icicle/include/icicle/api/stark252.h
- icicle/include/icicle/backend/msm_config.h
- icicle/include/icicle/fields/field.h
- icicle/include/icicle/msm.h
- icicle/tests/test_curve_api.cpp
- wrappers/rust/icicle-core/src/msm/mod.rs
This PR adds the chunked msm feature to V3
cuda-backend-branch: chunked-msm
> chunked-msm V3

- wrappers/rust/icicle-core/src/msm/mod.rs
- wrappers/rust/icicle-core/src/msm/tests.rs
This PR adds not shared bases option in rust bindings
> update msm wrappers

- docs/docs/icicle/getting_started.md
- docs/sidebars.js
Added summary on top of getting started and put getting started as the first page under ICICLE in sidebar
> getting started edits 

- icicle/backend/cpu/src/hash/cpu_merkle_tree.cpp
- icicle/include/icicle/backend/hash/hash_backend.h
- icicle/include/icicle/backend/merkle/merkle_tree_backend.h
- icicle/include/icicle/hash/hash.h
- icicle/include/icicle/merkle/merkle_tree.h
- icicle/run
- icicle/tests/test_hash_api.cpp
align the name of the function default_input_chunk_size across all.
cuda-backend-branch: naming-alignment
> naming alignemnt for default_input_chunk_size

- docs/docs/icicle/golang-bindings/hash.md
- docs/docs/icicle/primitives/hash.md
This PR adds docs for poseidon in golang bindings
> Golang poseidon docs

- icicle/backend/cpu/src/field/cpu_vec_ops.cpp
- icicle/tests/test_field_api.cpp
- icicle/tests/test_polynomial_api.cpp
cpu_poly_divide with columns_batch=true fixed
> support column batch for polynomial division CPU backend

- wrappers/rust/Cargo.toml
- wrappers/rust/icicle-core/src/ntt/mod.rs
- wrappers/rust/icicle-core/src/ntt/tests.rs
- wrappers/rust/icicle-fields/icicle-babybear/Cargo.toml
- wrappers/rust/icicle-fields/icicle-babybear/benches/ntt.rs
- wrappers/rust/icicle-fields/icicle-m31/src/fri/mod.rs
This PR 
- adds babybear Rust ntt benches
- adds on-device option to get more meaningful stats excluding data transfer
- more flexible launching by introducing bench range
Resolves #
> babybear ntt bench, added on-device option

- icicle/include/icicle/utils/rand_gen.h
- icicle/tests/test_base.h
- icicle/tests/test_curve_api.cpp
- icicle/tests/test_device_api.cpp
- icicle/tests/test_field_api.cpp
- icicle/tests/test_hash_api.cpp
Continuation of the previous rand PR - replacing every place rand() is called with a new rand_int function based on the same rand_generator in rand_gen.h - making test runs deterministic when given a fixed seed (Aiding debugging).
> Replace rand() with rand_uint_32b() for reproducibility

- scripts/release/Dockerfile.ubi8
- scripts/release/Dockerfile.ubi9
- scripts/release/Dockerfile.ubuntu20
- scripts/release/Dockerfile.ubuntu22
- scripts/release/README.md
- scripts/release/build_all.sh
install clang in release dockers to build release with clang instead of gcc
> install clang in release dockers

- icicle/backend/cpu/src/field/cpu_vec_ops.cpp
- icicle/include/icicle/vec_ops.h
add a vector operation to cpu backend that takes a vector of array and execute a program element wise
> add to cpu vecops the function execute_program

- .github/workflows/build-release-docker-img.yml
- .github/workflows/release.yml
- scripts/release/build_all.sh
This PR:
- Fixes the release script by ensuring nodejs is installed before trying to bump the docs version
- Moves building docker images for releases into a separate workflow as they only need to be rebuilt if prerequisite packages change
- Updates the release workflow and the build_all script to pull and use the latest docker images
> [FIX]: Add nodejs setup for release script

- icicle/include/icicle/program/program.h
- icicle/include/icicle/program/returning_value_program.h
- icicle/include/icicle/program/symbol.h
- icicle/tests/test_field_api.cpp
Add a program that receive a function that gets inputs and return a value
> Add-returnning-value-functiom-to-program

- icicle/backend/cpu/include/ntt_cpu.h
- icicle/include/icicle/curves/projective.h
- icicle/include/icicle/fields/field.h
- icicle/include/icicle/fields/host_math.h
- icicle/include/icicle/utils/modifiers.h
1. fix: ECNTT 5<logn<14 was single threaded. Now multi threaded.
2. This PR is using inlining and loop unrolling to improve CPU for:
- scalar multiplication
- scalar * ECpoint
- EC addition
- and consequently ECNTT and and MSM.
ECNTT (MULTI-THREAD) {size=2^14, curve=BN254}:
- For i9-13900k ubuntu22, clang-14: ~1200ms -> ~450ms (~2.6x)
- For m1-pro macos-15, clang-16: ~3500ms -> ~1200ms (~2.9x)
MSM (SINGLE-THREAD!) BLS12-377 logn=20:
- For i9-13900k ubuntu22, clang-14: ~32s -> ~10s (~3.2x)
- For m1-pro macos-15, clang-16:  ~36.5S  -> 13.3s (~2.7x)
MSM (MULTI-THREAD!) BLS12-377 logn=20:
- For i9-13900k ubuntu22, clang-14: ~1.9s -> ~1.9s (~1x) 
- For m1-pro macos-15, clang-16: ~5500ms -> ~3100ms (~1.8x)
CONCLUSION: ICICLE msm is bound by the manager thread. This is why for single thread we …
> performance: (~3x) optimize field multiplier and EC-adder for improved MSM and ECNTT

- icicle/CMakeLists.txt
- icicle/include/icicle/fields/field.h
- icicle/include/icicle/fields/host_math.h
This PR improves the barret multiplier by ~25% with a few tweaks:
- some more inlining
- loop ordering
As a result **_(Measured for BN254 single core on M1-pro)_**:
- scalar multiplication (1M elements):  ~27ms -> ~21.5ms (~1.25x) (Montgomery PR is  ~16.5ms **~1.3x faster**)
- EC adder (1K elements): ~0.36ms -> ~0.325ms (~1.1x) (Montgomery PR is  ~0.36ms **~1.1x slower**)
- MSM logn=12 (single core): 53ms --> 48ms (~1.1x) (Montgomery PR is ~53ms **~1.1x slower**)
- NTT logn=16 (single core): ~187ms --> ~165ms (~1.13x) (Montgomery PR is ~160ms **~1.03x faster**)
- ECNTT logn=10 (single core): ~ 402ms--> ~350ms (~1.15x) (Montgomery PR is ~ 350ms **~1x**)
> refine barret multiplier

- icicle/include/icicle/polynomials/default_backend/default_poly_backend.h
- wrappers/rust/icicle-core/src/polynomials/mod.rs
- Bug fix regarding copy_coeffs() in rust wrapper. When using a buffer larger than the poly to copy coeffs, invalid end-idx was computed.
- Better errors in poly-api and avoid crashing.
> fix bug in poly-api regarding copy_coeffs() in rust

- icicle/tests/test_field_api.cpp
this PR fixes ntt of size 1 in CUDA
cuda-backend-branch: fix-ntt-size-1
> fix ntt of size 1

- docs/docs/icicle/programmers_guide/cpp.md
- docs/docs/icicle/programmers_guide/general.md
- docs/docs/icicle/programmers_guide/go.md
- docs/docs/icicle/programmers_guide/rust.md
- icicle/include/icicle/device_api.h
- icicle/include/icicle/runtime.h
- icicle/src/device_api.cpp
- icicle/src/runtime.cpp
- icicle/tests/test_device_api.cpp
- wrappers/golang/runtime/device.go
- wrappers/golang/runtime/include/runtime.h
- wrappers/golang/runtime/tests/device_test.go
- wrappers/golang/runtime/tests/main_test.go
- wrappers/golang/runtime/tests/stream_test.go
- wrappers/rust/icicle-runtime/src/device.rs
- wrappers/rust/icicle-runtime/src/runtime.rs
- wrappers/rust/icicle-runtime/src/tests.rs
This PR adds the capability to set a default device for all threads. Setting a default device does not override a thread's explicitly set device
> Add capability to set a default device for all threads

- icicle/backend/cpu/src/field/cpu_vec_ops.cpp
Parallelize the execution of a program ov a vector on multiple threads using taskflow.
> Parallelize-vecop-program-execution

- icicle/backend/cpu/src/curve/cpu_msm.hpp
remove the thread launch that collapse all workers buckets into 1
move the collapse work to phase 2
> msm-avoid-double-thread-launch-on-phase1

- icicle/backend/cpu/src/hash/cpu_poseidon2.cpp
- icicle/tests/test_field_api.cpp
- icicle/tests/test_hash_api.cpp
This PR changes the Poseidon2 inputs data to be random instead of constant.
Resolves #
cuda-backend-branch:danny/poseidon2_sponge
> Change constant data of some poseidon2 tests to be random.

- icicle/include/icicle/device_api.h
- wrappers/rust/icicle-core/src/sumcheck/mod.rs
cuda-backend-branch: yshekel/auto_default_device
> Allow loaded backend to override default device for all threads

- scripts/format_all.sh
Fixed an issue with the `-output-replacements-xml` flag, which should have two dashes: `--output-replacements-xml`.  
With a single dash, it was interpreted as a series of separate flags (`-o`, `-u`, `-t`, `-p`, etc.), causing incorrect behavior. 
The command now works as expected.
> Fix incorrect clang-format flag

- .github/workflows/release.yml
Lock Release CI to run on a dedicated machine
> add "release" tag to Release CI workflow

- .gitignore
- icicle/include/icicle/fields/field.h
This PR fixes a build issue for small fields on mac (related to metal backend)
Resolves #
> [Fix] ModArith neg when b is u32

- README.md
- docs/docs/icicle/libraries.md
- docs/docs/icicle/primitives/poseidon.md
- docs/sidebars.ts
- docs/versioned_docs/version-3.2.0/icicle/libraries.md
- docs/versioned_docs/version-3.2.0/icicle/primitives/poseidon.md
Hi! Fixed several broken links in the documentation that pointed to outdated or non-existent pages. Key changes:
- Updated links to Stark252 in `libraries.md`.
- Fixed paths to Poseidon constants in `poseidon.md`, now pointing to the correct files.
- Updated the link to the Ingopedia community guide in `sidebars.ts`.
Everything should now open correctly.
> docs: fix broken links in libraries and poseidon sections

- icicle/include/icicle/program/program.h
- icicle/include/icicle/program/returning_value_program.h
- icicle/src/program/program_c_api.cpp
- icicle/src/symbol/symbol_api.cpp
- wrappers/rust/icicle-core/src/program/mod.rs
- wrappers/rust/icicle-core/src/sumcheck/mod.rs
- wrappers/rust/icicle-core/src/sumcheck/tests.rs
Fixed ReturningValueProgram creation in the rust wrapper
Added test checking Sumchek with a custom combine function
> Custom combine functions for sumcheck (ReturningValueProgram) in rust

- examples/c++/sumcheck/example.cpp
- icicle/backend/cpu/include/cpu_sumcheck.h
- icicle/include/icicle/backend/sumcheck_backend.h
- icicle/include/icicle/sumcheck/sumcheck.h
- icicle/include/icicle/sumcheck/sumcheck_transcript.h
- icicle/include/icicle/sumcheck/sumcheck_transcript_config.h
- icicle/tests/test_field_api.cpp
This PR addresses a critical issue in the SumcheckTranscript API where move semantics are improperly implemented due to the use of const rvalue references. This misuse leads to unintended copying of objects instead of moving them, which contradicts the original design intentions and can lead to performance degradation, especially since some of the data structures involved (like labels and public data) are potentially large.
Issues Addressed:
1. Const Rvalue Reference Misuse: The API currently accepts and stores configurations as const rvalue references (`const SumcheckTranscriptConfig<S>&&`). This approach mistakenly assumes that objects can be moved efficiently, but due to their constness, they are actually copied. This undermines the efficiency of move semantics.
2. Faulty Move …
> fix sumcheck transcript-config copy rather than move

- docs/docs/grants.md
- docs/versioned_docs/version-3.5.0/grants.md
- docs/versioned_docs/version-3.6.0/grants.md
This PR fixes the rendering on the grants page where text between non-escaped (\$ - vs escaped \\$) dollar signs are italicized
> [DOCS] Fix rendering italics from dollar sign

- wrappers/rust/icicle-curves/icicle-bls12-377/build.rs
- wrappers/rust/icicle-curves/icicle-bls12-381/build.rs
- wrappers/rust/icicle-curves/icicle-bn254/build.rs
- wrappers/rust/icicle-curves/icicle-bw6-761/build.rs
- wrappers/rust/icicle-curves/icicle-grumpkin/build.rs
- wrappers/rust/icicle-fields/icicle-babybear/build.rs
- wrappers/rust/icicle-fields/icicle-koalabear/build.rs
- wrappers/rust/icicle-fields/icicle-m31/build.rs
- wrappers/rust/icicle-fields/icicle-stark252/build.rs
This PR sets HASH to ON by default for all curves and fields in the Rust wrapper
> [Feat] Rust curves and fields to build with HASH

- wrappers/rust/icicle-runtime/src/runtime.rs
corrected the stream type to be of type `IcicleStreamHandle` (i.e., `*mut c_void`) for consistency across the interface.
p.s. previously, it was using `IcicleStreamHandle` as an alias, which caused some inconsistency with other functions like `icicle_malloc_async`.
now the types align properly.
> fix: stream type consistency with `IcicleStreamHandle` alias

- .github/workflows/cpp-golang-rust.yml
This PR fixes the Metal CI to skip FRI tests in Rust since FRI is not currently supported in Metal
Metal doesn't currently support FRI
> [FIX] Metal CI to skip FRI

- icicle/backend/cpu/CMakeLists.txt
This PR updates the cmake build process for CPU backend to only fetch Taskflow if it cannot be found on the system already.
This reduces build times for CPU backends considerably, especially in the CI
Build performance
> [FEAT] Download taskflow if not found on system

- icicle/backend/cpu/CMakeLists.txt
This PR fixes linking taskflow when found via find_package.
When taskflow is found via find_package, the `Taskflow_INCLUDE_DIR` should be set correctly, however it is set to `.`. It seems like the `CMAKE_PREFIX_PATH` might be an implied cwd for it. In any case, since Taskflow provides an imported target, it is better to use that along with `target_link_libraries`: https://cmake.org/cmake/help/v3.18/guide/using-dependencies/index.html#imported-targets-from-packages
> [FIX] Correctly link already installed taskflow

- .github/workflows/cpp-golang-rust.yml
This PR fixes the output name of the extracted cuda branch step. This was causing the ring and runtime jobs to rebuild every time they were run.
> [FIX] cuda branch output for ring and runtime build/tests

- .github/workflows/build-docs.yml
- .github/workflows/deploy-docs.yml
- docs/docs/icicle/golang-bindings.md
- docs/versioned_docs/version-3.7.0/icicle/golang-bindings.md
- docs/versioned_docs/version-3.8.0/icicle/golang-bindings.md
- docs/versioned_docs/version-3.9.0/icicle/golang-bindings.md
This PR fixes the docs deployment to use a reusable action instead of a local action.
> [FIX] Docs deployment

- icicle/tests/test_hash_api.cpp
- wrappers/rust/icicle-core/src/merkle/mod.rs
- wrappers/rust/icicle-fields/icicle-babybear/src/lib.rs
- wrappers/rust/icicle-fields/icicle-babybear/src/merkle/mod.rs
Note: The test is only for babybear because it fails for small fields and I don't think it's worth duplicating for all fields.
cuda-backend-branch: yshekel/merkle_tree_fix_padding
> fix merkle-tree default config and test for segfault

- wrappers/rust/icicle-core/src/merkle/mod.rs
- wrappers/rust/icicle-hash/src/tests.rs
Fix bug in the Merkle-Tree rust wrapper when using device-memory. 
> fix Merkle-Tree rust wrapper get_proof() for device-mem

- icicle/backend/cpu/include/cpu_sumcheck.h
- icicle/include/icicle/backend/sumcheck_backend.h
- icicle/include/icicle/sumcheck/sumcheck.h
- icicle/tests/test_field_api.cpp
In sumcheck - add get_challenge_vector method to let users get the challenges generated by the transcript
cuda-backend-branch: get_sumchecks_challanges
> [FEAT] add method to get challenges from sumcheck's Fiat-Shamir

- README.md
> Fixed devdocs link licensing 

- docs/docs/start/integration-&-support/colab-instructions.md
- docs/versioned_docs/version-3.1.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.2.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.3.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.4.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.5.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.6.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.7.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.8.0/icicle/colab-instructions.md
- docs/versioned_docs/version-3.9.0/start/integration-&-support/colab-instructions.md
This PR updates the collab instruction to checkout the correct ICICLE frontend that matches the backend used.
Resolves #905
> Fix collab instructions for version mismatch error

- wrappers/golang/runtime/tests/device_test.go
- wrappers/golang/runtime/tests/device_test_darwin.go
- wrappers/golang/runtime/tests/device_test_linux.go
- wrappers/golang/runtime/tests/memory_test.go
This PR fixes:
1. a hang in the Go memory tests when copying from device. The test was trying to copy more bytes than the source and destination sizes which caused a hang.
2. Fixes the naming of the Go memory tests
3. Go device tests actually run now.
4. Go device set default device test
> [FIX] Invalid memory access causes hang

- wrappers/rust/icicle-core/src/jl_projection/mod.rs
- wrappers/rust/icicle-core/src/jl_projection/tests.rs
- wrappers/rust/icicle-core/src/polynomial_ring.rs
- wrappers/rust/icicle-core/src/tests.rs
- wrappers/rust/icicle-runtime/src/memory.rs
Some APIs operate on scalar elements rather than polynomials. To use them with polynomial data, we need to reinterpret polynomial slices as flat slices of their scalar coefficients.
This PR introduces four functions to safely flatten HostSlice and DeviceSlice—both mutable and immutable—into corresponding slices of scalar elements.
> [FEAT] Add flattening utilities for polynomial slices into scalar slices

- .github/workflows/check-changed-files.yml
- .github/workflows/ci.yml
This PR adds a manual trigger for a full CI test suite
There are cases where we might want to test the entire test suite even if not all the features have changed. This enables manually triggering a full run of the test suites
> Add manual trigger for full test suite

- .github/workflows/ci.yml
- docs/docs/api/cpp/matrix_ops.md
- docs/docs/api/rust-bindings/ecntt.md
- docs/docs/api/rust-bindings/fri.md
- docs/docs/api/rust-bindings/hash.md
- docs/docs/api/rust-bindings/lattice/pqc-ml-kem.md
- docs/docs/api/rust-bindings/matrix_ops.md
- docs/docs/api/rust-bindings/merkle.md
- docs/docs/api/rust-bindings/msm.md
- docs/docs/api/rust-bindings/ntt.md
- docs/docs/api/rust-bindings/pairing.md
- docs/docs/api/rust-bindings/polynomials.md
- docs/docs/api/rust-bindings/program.md
- docs/docs/api/rust-bindings/sumcheck.md
- docs/docs/api/rust-bindings/vec-ops.md
- docs/docs/start/integration-&-support/migrate_from_v3.md
- docs/sidebars.ts
This PR updates Rust wrapper documentation for ICICLE V4
* Added matrix ops
* Added pairings
> ICICLE V4 documentation update

- icicle/include/icicle/fields/complex_extension.h
- icicle/include/icicle/fields/cubic_extension.h
- icicle/include/icicle/fields/quartic_extension.h
This PR removes the INLINE directive from the mul_wide methods in field extension classes (complex, cubic, and quartic). This change optimizes the build process by allowing the compiler to make better decisions about inlining these functions.
Reduce compile time as the compiler doesn't need to inline large functions at every call site
> [FEAT] Remove force inline from mul_wide

- icicle/include/icicle/fields/field.h
- icicle/include/icicle/fields/stark_fields/goldilocks.h
- icicle/include/icicle/fields/stark_fields/m31.h
- icicle/include/icicle/math/modular_arithmetic.h
- icicle/include/icicle/rings/integer_ring.h
This PR fixes the copy assignment operator for modular arithmetic in our C++ implementation.
* Implemented a copy assignment operator that handles modular arithmetic correctly.
* Added unit tests to verify the functionality of the copy assignment operator.
* Updated documentation to reflect the new behavior of the class.
> [FEAT] forward copy assignment in cpp

- scripts/release/build_release_and_tar.sh
This PR updates ICICLE release script to support rings and cuda pqc 
> [FEAT] update release script to support rings and CUDA PQC backend
